// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WEBAPIRestaurante.Datos;

#nullable disable

namespace WEBAPIRestaurante.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231029222201_MesasYOrdenes")]
    partial class MesasYOrdenes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WEBAPIRestaurante.Modelos.Mesa", b =>
                {
                    b.Property<int>("IdMesa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMesa"));

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<int>("Id_Orden")
                        .HasColumnType("int");

                    b.HasKey("IdMesa");

                    b.ToTable("Mesas");

                    b.HasData(
                        new
                        {
                            IdMesa = 1,
                            Estado = false,
                            Id_Orden = 0
                        },
                        new
                        {
                            IdMesa = 2,
                            Estado = false,
                            Id_Orden = 0
                        },
                        new
                        {
                            IdMesa = 3,
                            Estado = false,
                            Id_Orden = 0
                        },
                        new
                        {
                            IdMesa = 4,
                            Estado = false,
                            Id_Orden = 0
                        },
                        new
                        {
                            IdMesa = 5,
                            Estado = false,
                            Id_Orden = 0
                        },
                        new
                        {
                            IdMesa = 6,
                            Estado = false,
                            Id_Orden = 0
                        });
                });

            modelBuilder.Entity("WEBAPIRestaurante.Modelos.Orden", b =>
                {
                    b.Property<int>("Id_Orden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Orden"));

                    b.Property<DateTime>("FechaOrden")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdMesa")
                        .HasColumnType("int");

                    b.HasKey("Id_Orden");

                    b.ToTable("Ordenes");
                });

            modelBuilder.Entity("WEBAPIRestaurante.Modelos.Plato", b =>
                {
                    b.Property<int>("IdPlato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPlato"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Precio")
                        .HasColumnType("float");

                    b.HasKey("IdPlato");

                    b.ToTable("Menu");

                    b.HasData(
                        new
                        {
                            IdPlato = 1,
                            Descripcion = "Arroz Frito al estilo Chino muy rico",
                            ImagenUrl = "",
                            Nombre = "Chaulafan",
                            Precio = 4.5
                        },
                        new
                        {
                            IdPlato = 2,
                            Descripcion = "Arroz y Tallarin la mejor combi",
                            ImagenUrl = "",
                            Nombre = "Mixto",
                            Precio = 6.0
                        });
                });

            modelBuilder.Entity("WEBAPIRestaurante.Modelos.PlatoOrdenado", b =>
                {
                    b.Property<int>("Id_PlatoOrdenado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_PlatoOrdenado"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<bool>("Entregado")
                        .HasColumnType("bit");

                    b.Property<int>("IdPlato")
                        .HasColumnType("int");

                    b.Property<int?>("OrdenId_Orden")
                        .HasColumnType("int");

                    b.Property<int>("platoIdPlato")
                        .HasColumnType("int");

                    b.HasKey("Id_PlatoOrdenado");

                    b.HasIndex("OrdenId_Orden");

                    b.HasIndex("platoIdPlato");

                    b.ToTable("PlatosOrdenados");
                });

            modelBuilder.Entity("WEBAPIRestaurante.Modelos.PlatoOrdenado", b =>
                {
                    b.HasOne("WEBAPIRestaurante.Modelos.Orden", null)
                        .WithMany("pedido")
                        .HasForeignKey("OrdenId_Orden");

                    b.HasOne("WEBAPIRestaurante.Modelos.Plato", "plato")
                        .WithMany()
                        .HasForeignKey("platoIdPlato")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("plato");
                });

            modelBuilder.Entity("WEBAPIRestaurante.Modelos.Orden", b =>
                {
                    b.Navigation("pedido");
                });
#pragma warning restore 612, 618
        }
    }
}
