// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WEBAPIRestaurante.Datos;

#nullable disable

namespace WEBAPIRestaurante.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WEBAPIRestaurante.Modelos.Plato", b =>
                {
                    b.Property<int>("IdPlato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPlato"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Precio")
                        .HasColumnType("float");

                    b.HasKey("IdPlato");

                    b.ToTable("Menu");

                    b.HasData(
                        new
                        {
                            IdPlato = 1,
                            Descripcion = "Arroz Frito al estilo Chino muy rico",
                            ImagenUrl = "",
                            Nombre = "Chaulafan",
                            Precio = 4.5
                        },
                        new
                        {
                            IdPlato = 2,
                            Descripcion = "Arroz y Tallarin la mejor combi",
                            ImagenUrl = "",
                            Nombre = "Mixto",
                            Precio = 6.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
